import type { Metadata } from "next";
import { EB_Garamond, Faustina, Geist, Geist_Mono, Lexend, Slabo_13px } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { AIChatbot } from "@/components/modules/shared/AIChatbot";

import LoganFive from "next/font/local";

const loganFive = LoganFive({
    src: "../../public/fonts/LoganFiveW00Bold.ttf",
    variable : "--font-logan"
})

const ebGaramond = EB_Garamond({
  variable: "--font-eb-garamond",
  // subsets: ["latin"],
});

const lexend = Lexend({
    variable: "--font-lexend",
  subsets : ["latin"]
})


export const metadata: Metadata = {
  title: "SkillBridge",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${loganFive.variable} ${ebGaramond.variable} ${lexend.className}  antialiased`}
      >
          {children}
          <Toaster richColors/>
          <AIChatbot />
      </body>
    </html>
  );
}
